version: "3.8"

services:
   netsentry:
      build:
         context: .
         dockerfile: Dockerfile
      container_name: netsentry
      network_mode: "host"
      cap_add:
         - NET_ADMIN
         - NET_RAW
      volumes:
         - ./data:/app/data
         - ./configs:/app/configs
      ports:
         - "8080:8080"
         - "9090:9090"
      restart: unless-stopped
      environment:
         - NETSENTRY_LOG_LEVEL=info
         - NETSENTRY_ENABLE_API=true
         - NETSENTRY_ENABLE_WEB=true
      command: ["--api-enable", "--web-enable", "--config", "/app/configs/netsentry.yaml"]

   prometheus:
      image: prom/prometheus:latest
      container_name: prometheus
      volumes:
         - ./prometheus:/etc/prometheus
         - prometheus_data:/prometheus
      command:
         - "--config.file=/etc/prometheus/prometheus.yml"
         - "--storage.tsdb.path=/prometheus"
         - "--web.console.libraries=/etc/prometheus/console_libraries"
         - "--web.console.templates=/etc/prometheus/consoles"
         - "--web.enable-lifecycle"
      ports:
         - "9091:9090"
      restart: unless-stopped
      depends_on:
         - netsentry

   grafana:
      image: grafana/grafana:latest
      container_name: grafana
      volumes:
         - grafana_data:/var/lib/grafana
         - ./grafana/provisioning:/etc/grafana/provisioning
      environment:
         - GF_SECURITY_ADMIN_USER=admin
         - GF_SECURITY_ADMIN_PASSWORD=netsentry
         - GF_USERS_ALLOW_SIGN_UP=false
      ports:
         - "3000:3000"
      restart: unless-stopped
      depends_on:
         - prometheus

volumes:
   prometheus_data:
   grafana_data:
