global:
   scrape_interval: 15s
   evaluation_interval: 15s

scrape_configs:
   - job_name: "netsentry"
     static_configs:
        - targets: ["localhost:9091"]
     metrics_path: "/metrics"

   - job_name: "prometheus"
     static_configs:
        - targets: ["localhost:9090"]

alerting:
   alertmanagers:
      - static_configs:
           - targets:
             # - alertmanager:9093

rule_files:
   - "rules/*.yml"
